In [1]:
text="""Gender equality is, first and foremost, a human right. A woman is entitled to live in dignity and in freedom from want and from fear. Empowering women is also an indispensable tool for advancing development and reducing poverty. Empowered women contribute to the health and productivity of whole families and communities and to improved prospects for the next generation. The importance of gender equality is underscored by its inclusion as one of the eight Millennium Development Goals. Gender equality is acknowledged as being a key to achieving the other seven goals. Yet discrimination against women and girls - including gender-based violence, economic discrimination, reproductive health inequities, and harmful traditional practices - remains the most pervasive and persistent form of inequality. Women and girls bear enormous hardship during and after humanitarian emergencies, especially armed conflicts. There have been several organisations and institutions advocating for women, promoting legal and policy reforms and gender-sensitive data collection, and supporting projects that improve women's health and expand their choices in life. Despite many international agreements affirming their human rights, women are still much more likely than men to be poor and illiterate. They usually have less access than men to medical care, property ownership, credit, training and employment. They are far less likely than men to be politically active and far more likely to be victims of domestic violence. The ability of women to control their own fertility is absolutely fundamental to women’s empowerment and equality. When a woman can plan her family, she can plan the rest of her life. When she is healthy, she can be more productive. And when her reproductive rights — including the right to decide the number, timing and spacing of her children, and to make decisions regarding reproduction free of discrimination, coercion and violence — are promoted and protected, she has freedom to participate more fully and equally in society. Gender equality implies a society in which women and men enjoy the same opportunities, outcomes, rights and obligations in all spheres of life. Equality between men and women exists when both sexes are able to share equally in the distribution of power and influence; have equal opportunities for financial independence through work or through setting up businesses; enjoy equal access to education and the opportunity to develop personal ambitions. A critical aspect of promoting gender equality is the empowerment of women, with a focus on identifying and redressing power imbalances and giving women more autonomy to manage their own lives. Women's empowerment is vital to sustainable development and the realization of human rights for all. Where women’s status is low, family size tends to be large, which makes it more difficult for families to thrive. Population and development and reproductive health programmes are more effective when they address the educational opportunities, status and empowerment of women. When women are empowered, whole families benefit, and these benefits often have ripple effects to future generations. The roles that men and women play in society are not biologically determined - they are socially determined, changing and changeable. Although they may be justified as being required by culture or religion, these roles vary widely by locality and change over time. Key issues and linkages: 1)Reproductive health: Women, for both physiological and social reasons, are more vulnerable than men to reproductive health problems. Reproductive health problems, including maternal mortality and morbidity, represent a major - but preventable - cause of death and disability for women in developing countries. Failure to provide information, services and conditions to help women protect their reproduction health therefore constitutes gender-based discrimination and a violation of women’s rights to health and life. 2) Stewardship of natural resources: Women in developing nations are usually in charge of securing water, food and fuel and of overseeing family health and diet. Therefore, they tend to put into immediate practice whatever they learn about nutrition and preserving the environment and natural resources. Economic empowerment: More women than men live in poverty. Economic disparities persist partly because much of the unpaid work within families and communities falls on the shoulders of women and because they face discrimination in the economic sphere. Educational empowerment: About two thirds of the illiterate adults in the world are female. Higher levels of women's education are strongly associated with both lower infant mortality and lower fertility, as well as with higher levels of education and economic opportunity for their children. Political empowerment: Social and legal institutions still do not guarantee women equality in basic legal and human rights, in access to or control of land or other resources, in employment and earning, and social and political participation. Laws against domestic violence are often not enforced on behalf of women. Experience has shown that addressing gender equality and women’s empowerment requires strategic interventions at all levels of programming and policy-making. Women’s Work and Economic Empowerment: In nearly every country, women work longer hours than men, but are usually paid less and are more likely to live in poverty. In subsistence economies, women spend much of the day performing tasks to maintain the household, such as carrying water and collecting fuel wood. In many countries women are also responsible for agricultural production and selling. Often they take on paid work or entrepreneurial enterprises as well. Unpaid domestic work – from food preparation to care giving – directly affects the health and overall well being and quality of life of children and other household members. The need for women’s unpaid labour often increases with economic shocks, such as those associated with the AIDS pandemic or economic restructuring. Yet women's voices and lived experiences – whether as workers (paid and unpaid), citizens, or consumers – are still largely missing from debates on finance and development. Poor women do more unpaid work, work longer hours and may accept degrading working conditions during times of crisis, just to ensure that their families survive. Intergenerational gender gaps: The differences in the work patterns of men and women, and the 'invisibility' of work that is not included in national accounts, lead to lower entitlements to women than to men. Women’s lower access to resources and the lack of attention to gender in macroeconomic policy adds to the inequity, which, in turn, perpetuates gender gaps. For example, when girls reach adolescence they are typically expected to spend more time in household activities, while boys spend more time on farming or wage work. By the time girls and boys become adults; females generally work longer hours than males, have less experience in the labour force, earn less income and have less leisure, recreation or rest time. This has implications for investments in the next generation. If parents view daughters as less likely to take paid work or earn market wages, they may be less inclined to invest in their education, women's fastest route out of poverty. Empowering Women through Education: "Education is one of the most important means of empowering women with the knowledge, skills and self-confidence necessary to participate fully in the development process." 

"""

In [2]:
pip install regex

Note: you may need to restart the kernel to use updated packages.


In [3]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\CSE_IT\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\CSE_IT\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.tokenize import sent_tokenize,word_tokenize
import regex

#tokenize sentences 
def tokenize_sentence(text):
  sents=sent_tokenize(text) 
  sent_list=[]
  for sent in sents:
    sent=sent.strip()
    sent=sent.lower() 
    sent_list.append(sent)
  return(sent_list)


sentences=tokenize_sentence(text)
sent_for_print=sentences
print(sentences)

['gender equality is, first and foremost, a human right.', 'a woman is entitled to live in dignity and in freedom from want and from fear.', 'empowering women is also an indispensable tool for advancing development and reducing poverty.', 'empowered women contribute to the health and productivity of whole families and communities and to improved prospects for the next generation.', 'the importance of gender equality is underscored by its inclusion as one of the eight millennium development goals.', 'gender equality is acknowledged as being a key to achieving the other seven goals.', 'yet discrimination against women and girls - including gender-based violence, economic discrimination, reproductive health inequities, and harmful traditional practices - remains the most pervasive and persistent form of inequality.', 'women and girls bear enormous hardship during and after humanitarian emergencies, especially armed conflicts.', "there have been several organisations and institutions advoc

In [5]:
from nltk.tokenize import sent_tokenize,word_tokenize
import regex
import string
def remove_punctuation(sentences):
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    str=""
    for i in range(len(words)):
      x=regex.sub("[^\w\s]|_","",words[i]).strip()
      str=str+" "+x
      str=str.strip()
    sent_list.append(str)
  return sent_list

sentences=remove_punctuation(sentences)
print(sentences)

['gender equality is first and foremost a human right', 'a woman is entitled to live in dignity and in freedom from want and from fear', 'empowering women is also an indispensable tool for advancing development and reducing poverty', 'empowered women contribute to the health and productivity of whole families and communities and to improved prospects for the next generation', 'the importance of gender equality is underscored by its inclusion as one of the eight millennium development goals', 'gender equality is acknowledged as being a key to achieving the other seven goals', 'yet discrimination against women and girls including genderbased violence economic discrimination reproductive health inequities and harmful traditional practices remains the most pervasive and persistent form of inequality', 'women and girls bear enormous hardship during and after humanitarian emergencies especially armed conflicts', 'there have been several organisations and institutions advocating for women pro

In [6]:

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
def remove_stopwords(sentences):
  stop_words=set(stopwords.words("english"))
   
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    words=[word for word in words if word not in stop_words]
    words=" ".join(words)
    words=words.strip()
    sent_list.append(words)
  return sent_list

sentences=remove_stopwords(sentences)
print(sentences)

['gender equality first foremost human right', 'woman entitled live dignity freedom want fear', 'empowering women also indispensable tool advancing development reducing poverty', 'empowered women contribute health productivity whole families communities improved prospects next generation', 'importance gender equality underscored inclusion one eight millennium development goals', 'gender equality acknowledged key achieving seven goals', 'yet discrimination women girls including genderbased violence economic discrimination reproductive health inequities harmful traditional practices remains pervasive persistent form inequality', 'women girls bear enormous hardship humanitarian emergencies especially armed conflicts', 'several organisations institutions advocating women promoting legal policy reforms gendersensitive data collection supporting projects improve women health expand choices life', 'despite many international agreements affirming human rights women still much likely men poor i

In [9]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

def remove_stemming(sentences):
  stemmer=PorterStemmer()
  sent_list=[]
  for sent in sentences:
    words=word_tokenize(sent)
    words=[stemmer.stem(word) for word in words]
    words=" ".join(words)
    sent_list.append(words)
  return sent_list

sentences=remove_stemming(sentences)
print(sentences)

['gender equal first foremost human right', 'woman entitl live digniti freedom want fear', 'empow women also indispen tool advanc develop reduc poverti', 'empow women contribut health product whole famili commun improv prospect next gener', 'import gender equal underscor inclu one eight millennium develop goal', 'gender equal acknowledg key achiev seven goal', 'yet discrimin women girl includ genderba violenc econom discrimin reproduct health inequ harm tradit practic remain perva persist form inequ', 'women girl bear enorm hardship humanitarian emerg especi arm conflict', 'sever organi institut advoc women promot legal polici reform gendersensit data collect support project improv women health expand choic life', 'despit mani intern agreement affirm human right women still much like men poor illit', 'usual less access men medic care properti ownership credit train employ', 'far less like men polit activ far like victim domest violenc', 'abil women control fertil absolut fundament wome

In [10]:
from nltk.tokenize import word_tokenize

### optional - just to know the sentence , and the number of words in that sentence 
def sentence_information(sentences):
  sent_info=[]
  for i,sent in enumerate(sentences):
    words=word_tokenize(sent)
    sent_dict={"sent_id":i,"sent_word_count":len(words)}
    sent_info.append(sent_dict)
    
  return sent_info
    
sent_info=sentence_information(sentences)
print(sent_info)

[{'sent_id': 0, 'sent_word_count': 6}, {'sent_id': 1, 'sent_word_count': 7}, {'sent_id': 2, 'sent_word_count': 9}, {'sent_id': 3, 'sent_word_count': 12}, {'sent_id': 4, 'sent_word_count': 10}, {'sent_id': 5, 'sent_word_count': 7}, {'sent_id': 6, 'sent_word_count': 20}, {'sent_id': 7, 'sent_word_count': 10}, {'sent_id': 8, 'sent_word_count': 20}, {'sent_id': 9, 'sent_word_count': 14}, {'sent_id': 10, 'sent_word_count': 11}, {'sent_id': 11, 'sent_word_count': 11}, {'sent_id': 12, 'sent_word_count': 9}, {'sent_id': 13, 'sent_word_count': 6}, {'sent_id': 14, 'sent_word_count': 2}, {'sent_id': 15, 'sent_word_count': 24}, {'sent_id': 16, 'sent_word_count': 13}, {'sent_id': 17, 'sent_word_count': 26}, {'sent_id': 18, 'sent_word_count': 17}, {'sent_id': 19, 'sent_word_count': 8}, {'sent_id': 20, 'sent_word_count': 11}, {'sent_id': 21, 'sent_word_count': 12}, {'sent_id': 22, 'sent_word_count': 11}, {'sent_id': 23, 'sent_word_count': 11}, {'sent_id': 24, 'sent_word_count': 12}, {'sent_id': 25, '

In [15]:
from nltk.tokenize import word_tokenize
import matplotlib.pyplot as plt

## counting the frequency of every word in sentences
def frequency_of_words(sentences):
  freq_info=[]
  for i,sent in enumerate(sentences):
    words=word_tokenize(sent)
    frequency_dict={}
    for word in words:
      if word in frequency_dict.keys():
        frequency_dict[word]=frequency_dict[word]+1
      else:
        frequency_dict[word]=1
    temp={"sent_id":i,"frequency_of_word":frequency_dict}
    freq_info.append(temp)
    
  return freq_info

freq_info=frequency_of_words(sentences)

h=[]
l=[]
unique_words=unique_word(sentences)
for i,word in enumerate(unique_words):
  count=0
  for sent in sentences:
    words=word_tokenize(sent)
    for word_1 in words:
      if word==word_1:
        count=count+1
  l.append(i)
  h.append(count)
  
    
print(freq_info)

[{'sent_id': 0, 'frequency_of_word': {'gender': 1, 'equal': 1, 'first': 1, 'foremost': 1, 'human': 1, 'right': 1}}, {'sent_id': 1, 'frequency_of_word': {'woman': 1, 'entitl': 1, 'live': 1, 'digniti': 1, 'freedom': 1, 'want': 1, 'fear': 1}}, {'sent_id': 2, 'frequency_of_word': {'empow': 1, 'women': 1, 'also': 1, 'indispen': 1, 'tool': 1, 'advanc': 1, 'develop': 1, 'reduc': 1, 'poverti': 1}}, {'sent_id': 3, 'frequency_of_word': {'empow': 1, 'women': 1, 'contribut': 1, 'health': 1, 'product': 1, 'whole': 1, 'famili': 1, 'commun': 1, 'improv': 1, 'prospect': 1, 'next': 1, 'gener': 1}}, {'sent_id': 4, 'frequency_of_word': {'import': 1, 'gender': 1, 'equal': 1, 'underscor': 1, 'inclu': 1, 'one': 1, 'eight': 1, 'millennium': 1, 'develop': 1, 'goal': 1}}, {'sent_id': 5, 'frequency_of_word': {'gender': 1, 'equal': 1, 'acknowledg': 1, 'key': 1, 'achiev': 1, 'seven': 1, 'goal': 1}}, {'sent_id': 6, 'frequency_of_word': {'yet': 1, 'discrimin': 2, 'women': 1, 'girl': 1, 'includ': 1, 'genderba': 1, '

In [20]:
def unique_word(sentences):
  unique=[]
  for sents in sentences:
    for word in word_tokenize(sents):
      if word not in unique:
        unique.append(word)
  return unique
unique_words=unique_word(sentences)
print(len(unique_words))

360


'\ndef unique_word(sentences):\n  unique=[]\n  for sents in sentences:\n    for word in word_tokenize(sents):\n      if word not in unique:\n        unique.append(word)\n  return unique\nunique_words=unique(sentences)\nprint(len(unique))\n'

In [27]:
import numpy as np

#term frequency calc and print matrix 
def tf_calculation(sent_info,freq_info):
  tf_values=np.zeros(shape=(len(sent_info),len(unique_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      tf=freq_info_dict["frequency_of_word"][word]/sent_info[i]["sent_word_count"]
      tf_values[i][unique_words.index(word)]=tf
  return tf_values
   
  
tf_values=tf_calculation(sent_info,freq_info)
print(tf_values)

[[0.16666667 0.16666667 0.16666667 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.05882353 0.05882353 0.05882353]]


In [28]:
import math

# idf calc 
def idf_calculate(sent_info,freq_info):
  idf_values=np.zeros(shape=(len(sent_info),len(unique_words)))
  for i,freq_info_dict in enumerate(freq_info):
    for word in freq_info_dict["frequency_of_word"].keys():
      sum=0
      for word_in_dict in freq_info:
        if word in set(word_in_dict["frequency_of_word"].keys()):
          sum=sum+word_in_dict["frequency_of_word"][word]
      idf_values[i][unique_words.index(word)]=math.log(len(sentences)/sum)
  return idf_values
        
idf_values=idf_calculate(sent_info,freq_info)
print(idf_values)

[[1.75401914 1.38629436 3.95124372 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 3.95124372 3.95124372 3.95124372]]


In [23]:
import numpy as np

#tfidf
def tfidf_calculation(tf_values,idf_values):
  tfidf_values=np.zeros(shape=(len(sent_info),len(unique_words)))
  tfidf_values=np.multiply(tf_values,idf_values)
  return tfidf_values

tfidf_values=tfidf_calculation(tf_values,idf_values)
print(tfidf_values)

[[0.29233652 0.23104906 0.65854062 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.2324261  0.2324261  0.2324261 ]]


In [24]:
import numpy as np
import math
# finding the cosine similarity 

def cosine_similarity(sent_1,sent_2):
  s1_dot_s2=np.sum(np.multiply(sent_1,sent_2))
  magnitude_of_s1=math.sqrt(np.sum(np.multiply(sent_1,sent_1)))
  magnitude_of_s2=math.sqrt(np.sum(np.multiply(sent_2,sent_2)))
  return s1_dot_s2/(magnitude_of_s1*magnitude_of_s2)

In [29]:


def cosine_matrix(tfidf_values):
  cosine_similarity_matrix=np.zeros(shape=(len(sentences),len(sentences)))
  for i in range(len(tfidf_values)):
    for j in range(len(tfidf_values)):
      cosine_similarity_matrix[i][j]=cosine_similarity(tfidf_values[i],tfidf_values[j])
    
#normalize the matrix
  for idx in range(len(cosine_similarity_matrix)):
    cosine_similarity_matrix[idx] /= cosine_similarity_matrix[idx].sum()
    
  return cosine_similarity_matrix

cosine_similarity_matrix=cosine_matrix(tfidf_values)
print(cosine_similarity_matrix)

[[0.45882088 0.         0.         ... 0.         0.         0.        ]
 [0.         0.63033537 0.         ... 0.         0.         0.        ]
 [0.         0.         0.52102917 ... 0.         0.02686795 0.02983225]
 ...
 [0.         0.         0.         ... 0.64958672 0.07487248 0.        ]
 [0.         0.         0.02106123 ... 0.04707564 0.40842386 0.01651242]
 [0.         0.         0.02661913 ... 0.         0.01879618 0.46491097]]


In [34]:
# textrank using cosine matrix 


def text_rank(cosine_matrix):
  tpf=np.ones(len(sentences))/len(sentences)
  i=0
  while i<100:
    new_p=np.dot(cosine_similarity_matrix.T,tpf.T)
    if i<=100:
      return new_p
    i=i+1
    tpf = new_p
  
  
result_rank=text_rank(cosine_similarity_matrix)
print(len(sentences))
rank_with_sentence={}
for i in range(len(sent_for_print)):
  if result_rank[i] not in set(rank_with_sentence.keys()):
    rank_with_sentence[result_rank[i]]=[sent_for_print[i]]
  else:
    rank_with_sentence[result_rank[i]].append(sent_for_print[i])
    

#ranked sentences o/p => 1/4th of the original !!!

for key in sorted(rank_with_sentence.keys(),reverse=True)[:int(len(rank_with_sentence.keys())/4)]:
  for k in rank_with_sentence[key]:
    #print(key,k)
    k[0].upper()
    print(k)

52
women’s work and economic empowerment: in nearly every country, women work longer hours than men, but are usually paid less and are more likely to live in poverty.
economic empowerment: more women than men live in poverty.
empowered women contribute to the health and productivity of whole families and communities and to improved prospects for the next generation.
and when her reproductive rights — including the right to decide the number, timing and spacing of her children, and to make decisions regarding reproduction free of discrimination, coercion and violence — are promoted and protected, she has freedom to participate more fully and equally in society.
political empowerment: social and legal institutions still do not guarantee women equality in basic legal and human rights, in access to or control of land or other resources, in employment and earning, and social and political participation.
population and development and reproductive health programmes are more effective when th